### ISSUE TITLE
medhat.tarek1000@gmail.com

### ISSUE THREAD

**Issue by Medhatt21** [utiasSTARS/ALLO#1]
Downloading the dataset is unfeasible. DiskStation has a very low download rate (less than 512KB). Is there a possibility to upload the dataset to a different platform (GoogleDrive, DropBox, etc...)

**Comment by joonielee832** [comment]
The issue should now be fixed. Please try it again and let us know if you encounter the same problem.

**Comment by johncwlee** [comment]
Hi, thank you for your interest in our dataset. The link is now fixed and remote download speed should be much faster. Please let us know if you encounter any other issues.
